info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    account: 
      path: /patients/**
      serviceId: prodent-patient-service
    customer: 
      path: /appointments/**
      serviceId: prodent-appointment-service

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
      
server:
  port: 8765
  session:
      timeout: 800000

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG